engines:
  csslint: 
    enabled: true
  duplication: 
    config: ~
    enabled: true
    languages: 
      - javascript
  eslint: 
    enabled: true
  golint: 
    enabled: true
  rubocop: 
    enabled: false
exclude_paths: 
  - test/**/*
  - node_modules/**/*
  - docs/*
  - docs/**/*
  - gulp-tasks/*
  - src/public/bower_components/**/*
ratings: 
  paths: 
    - src/routes/**/*
    - src/routes/*
    - src/public/components/**/*
    - src/public/services/**/*
    - src/public/templates/**/*
    - src/public/app.js
