engines:
  csslint: 
    enabled: true
    exclude_fingerprints:
      - 37dd32f7d1ed309ee32af4dc4b935489
      - 37dd32f7d1ed309ee32af4dc4b935489
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
  eslint: 
    enabled: true
  golint: 
    enabled: true
exclude_paths: 
  - test/**/*
  - node_modules/**/*
  - docs/*
  - docs/**/*
  - gulp-tasks/*
  - src/public/bower_components/**/*
  - dist/*
  - gulpfile.js
ratings: 
  paths: 
    - src/routes/**/*
    - src/routes/*
    - src/public/components/**/*
    - src/public/services/**/*
    - src/public/templates/**/*
    - src/public/app.js
    - src/app.js
