engines:
  csslint: 
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
    checks:
      Similar code:
        enabled: false
  eslint: 
    enabled: true
  golint: 
    enabled: true
exclude_paths: 
  - test/**/*
  - node_modules/**/*
  - docs/*
  - docs/**/*
  - gulp-tasks/*
  - src/public/bower_components/**/*
ratings: 
  paths: 
    - src/routes/**/*
    - src/routes/*
    - src/public/components/**/*
    - src/public/services/**/*
    - src/public/templates/**/*
    - src/public/app.js
