engines:
  csslint: 
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
    exclude_fingerprints:
      - d1f6e82231068d565aa0b72941818070
  eslint: 
    enabled: true
  golint: 
    enabled: true
exclude_paths: 
  - test/**/*
  - node_modules/**/*
  - docs/*
  - docs/**/*
  - gulp-tasks/*
  - src/public/bower_components/**/*
ratings: 
  paths: 
    - src/routes/**/*
    - src/routes/*
    - src/public/components/**/*
    - src/public/services/**/*
    - src/public/templates/**/*
    - src/public/app.js
    - src/app.js
