language: node_js
node_js:
- '6.3'
services:
  - mongodb
before_script:
- bower install
- mongo --version
- mongorestore --db spielplan-test --drop test/backend/database-setup/data/spielplan
script: gulp test:travis
addons:
  sauce_connect:
    username: "BerniWittmann"
  jwt:
    secure: zrI5SQ6alxg8VT4lHUdNGkJeCsSx3tnB2eRQ+86MwEEgr5gsMPiA88fsWMPpMzJ5uO2pqi2QA/bosfi9glxFVPKcdFvlSwP/RBO0lVPUfIa4UeIsBXOmEPtgMUTdOBmLNjd2WfMGPl6avZWphGiWt4b3Q2db49VM7cr6kmkMs824YvRZPrGLF75Ips/KC7HieLwIq9gf7hJRm1HwC7AkKXXpYfDo+lOpa41IqlHcBJMzeiTPk+42tqGTpg59WZihNSZbHoFYYMyUg9bgkxbqh7z+oMcsCpzWw9bwWkKb/6jsn8u2lRyvcZkRxNEMZ78AO3Zkyva1/k39inKZJQqe152C2/m+FCejhUMQA1cVeOhk7xiUjahGohXTP34D6HHKzX8Af3JnyprKY+NmA7W1/cu7+O3IcyeOu+6ZFSf+TI/uTPTTI7BPauh0B7oOwoA0IsSfRTNkreQLBi7RrR1EbLF4i4J9RYkbSyjKuCwqLVRGFpD3u+P40s3kwOO6qtSKR7k8b+mZO2LttgXsqFF9L1dT+Ng+Iqqy5hOvn2uQpcByVLIutAgjU5jCj1oyGuDRP/qFb5hL41PSj9RbW7gLHtCA0hpHfrC6z8p++F5cTD+VMvU8WANNeZfo1eosNRKmWj02YYddIf+CqY/f13fjt+Fv9DUEmaI6a9cT+KPoAHE=
branches:
  only:
  - master
  - develop
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  api_key:
    secure: UFoQ+NAVA5Ynm7hihxHKnSxfMuIlTwvVG5eUKmWZvAIfM3JwCWTbX6GpA5aIsqc9n7at128DLiITRk3H2e9UJlumH3WIU2tzWQb1+6irF7MaudAm49SgEcXG5AjEqIu5ikSXM4QCBNVdcZKQwW52GPL3j7owBWMPFf/8Lcgx24noZCXbK/K+RwCpYfpLQs/W4v8Sj4V8vHoSoVf4vyAmXWou3CyC6KVCAXJUjAIMHS3p1kbNecs5CgfXFVY/Gbfs0O0RmBFElaCd6WrljWil3TlVd/+iLATDWShzZE1ux8OUTBWBRGSnYs0U7QY/XWeensw0xAAky7E5R+DNHdr25tpllimMAzFJoCVeJXWXjUM04E71WFTdGT5Sk3Z5BYKKjc8fja81R551OlbD38wKyrDvs42vdFhX1KACzOtQ/aINz20qeEAEoppQ8sIglhwSdL2TI7gTv75vtKULZ8CQIjamW7mobgjT9pajNWdIrqaFT12szRkgv/LpAqRfBPP3S435JcZg7WQ88sEwKE/QV3NZ7+7HZ8BQ1kSih2AR1jLCD/nqKB4qtCgWE7eaMpne0bOyFHrI3dJVa+WRYYJOQzejFMCtdTMONrjMdtT6JEH9RRH+QAyMHCXRnqCCtKIIB6Q1NqEXYqNfRCI56/cPRHf+QQZFSCVb0I/6mbywvLM=
  app:
    master: spielplanismaning
    develop: spielplanismaning-testing
notifications:
  slack:
    on_pull_requests: false
    rooms:
      secure: iMFuDbqhVhvMxuWyrRx3xkhMXYchW9fYiVfWMMPdKqMdEAps9lpZ5W5pYkBgCCS+XDamVforN5zG1H8qrCkMkm8x+TXdM7FHOzgnlW+D8ufDXFoMF9kz4DR45fopHCUHJh3HM32zKqxEfPA5uiRN9dLf59dlogQ/TpX7h3fp2jrRGjDBLJw58hg0IwsZB3xQZkNzKT3qzQEdH2KRWB0Xgs1Ksan4PrD3ev9/d0vA0lpDHIJR7ynnnqdXIMs8DoFd+6fGLdvS6zZIXMNzdot46HvP1YoJEaw1p8Xcnk2EfAELQI2nnPFnzLv254+hAJAratzDuYA0VcjxJXx7/UOeFq4KoDfm1/K9puNOF4tZgGHi+PLOmqtFH52Un+zTQr9biW1nGq/UFLK4Ti+MrbwnL0i+i9uWBKC/2aVw0J1agxT3hJLqzi1qCsbXS/JqtRQrQhI4ZqRLU3Lz19CEmhezN2voTGIEyJZ6R2TQkzskr+Tg0sDgqMaX7tcVw4cdXCnFpLcYWKXsP+PMg0qEtSzA0Xn8zvW6E6KaAtLoJ1GBo6O8HLcSgMIzFIgwHN50SvTBY15Xu7dodS3K+WQu+OEP8tW3sum/o2f82MlytlsudbMcAVmctLMou/b7ThiIv1mFaVyFNUvBhtfz+Mq1CjJHkrBj65ne8c/9uE2V9j2F010=
  email:
    recipients:
      - b.wittmann@mail.de
    on_success: never
    on_failure: always