language: node_js
node_js:
- '6.3'
before_script:
- npm install
- bower install
script: gulp test
branches:
  only:
  - master
  - develop
deploy:
  provider: heroku
  api_key:
    secure: UFoQ+NAVA5Ynm7hihxHKnSxfMuIlTwvVG5eUKmWZvAIfM3JwCWTbX6GpA5aIsqc9n7at128DLiITRk3H2e9UJlumH3WIU2tzWQb1+6irF7MaudAm49SgEcXG5AjEqIu5ikSXM4QCBNVdcZKQwW52GPL3j7owBWMPFf/8Lcgx24noZCXbK/K+RwCpYfpLQs/W4v8Sj4V8vHoSoVf4vyAmXWou3CyC6KVCAXJUjAIMHS3p1kbNecs5CgfXFVY/Gbfs0O0RmBFElaCd6WrljWil3TlVd/+iLATDWShzZE1ux8OUTBWBRGSnYs0U7QY/XWeensw0xAAky7E5R+DNHdr25tpllimMAzFJoCVeJXWXjUM04E71WFTdGT5Sk3Z5BYKKjc8fja81R551OlbD38wKyrDvs42vdFhX1KACzOtQ/aINz20qeEAEoppQ8sIglhwSdL2TI7gTv75vtKULZ8CQIjamW7mobgjT9pajNWdIrqaFT12szRkgv/LpAqRfBPP3S435JcZg7WQ88sEwKE/QV3NZ7+7HZ8BQ1kSih2AR1jLCD/nqKB4qtCgWE7eaMpne0bOyFHrI3dJVa+WRYYJOQzejFMCtdTMONrjMdtT6JEH9RRH+QAyMHCXRnqCCtKIIB6Q1NqEXYqNfRCI56/cPRHf+QQZFSCVb0I/6mbywvLM=
  app:
    master: spielplanismaning
    develop: spielplanismaning-testing
notifications:
  slack:
    secure: veEJwQmx6XytP80Kqcb0kRpbU1vR6at9ZSCxqYbLMn8n3xIByh+PCIS3Mzcul3ol/+mmby4Tt4/W7RCTuW+/pB0yAPslgxdqDo56kcfzDJv4AnxMRCpnbT5sLFJkM5orAzcnYw9DyMaZvBSmDqBscpZ66hXpkK4Uh1zyfl8Of3a9bZbnVYIaBGbwpLZ3ocjjLPidd1bWspqUk7xxd9ZuzRWNgrujXAVFEfZWmeBljVs3cff0LhwphGh+z5ukYr1SbuCZGteunE33BkD5ubfYtvCBt3L15LfCnpX88csI+JgoXa3FIr0jpM4Fi9y7XeaJB3ocVPa1+aU2T1bwUc3wP3AHaHGqL2Bvh4F8e6dXvP0Km/e1S8XowYFJqxvc1IKGE3u2GLB2Ax7bvbE9a1KzbEyLfV6divweUwUBNhJ39crUe9pUoMMbhHM0jJysfdHXkfZH1nfxYxpAap2I8Fx6XkJKJV37Mcqi6gprm/nKKd8SnzCOVB/WYJdgsM0+BMcQlvgvWOMx5XmmYVRXVgA8GJQ2f8zVI/9vMcmLPf3zwUhg/3oRZ/2UunaMKIYXwcI2aCh2aLGco8tHDjcfdDuWyxOYiicfb8H6ayXvmsr3bscJ51HeFNSG+9YSOtOsJT+HEtcR522e84j/gtPs+slKyexoaPKi2CeZh9/EfubRV38=
