language: node_js
node_js:
- '6.3'
services:
  - mongodb
before_script:
- bower install
- mongo --version
- mongorestore --db spielplan-test --drop test/backend/database-setup/data/spielplan
script: gulp test:travis
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  sauce_connect:
    username: "BerniWittmann"
  jwt:
    secure: "XHQdTn6IRmAZzbcnkL0EYu8HvL8HSeDPLUqRcCLHXY/+hJTEbKCJJkZaublLwtsOrX9PQkV0Bg4tr16+BbeRX65jeDxPRm4sEXa3Z2E/i2zbwHTNf38DctHR2kqpIUWTKsy3NkJl2ayYk1Je4QcJKKFlSrSbfDgH0wUSo/9Mi57HkmGf7q+fewtcIrGzT4i3GFXd6cf+K8+lzOIHZUc0TPsxCcW6dJvWDU72Y6OftCWzxIgzUDd+/seAQe2kC1meMDtI9A9x1oBJeIxCfhr3KPpHZTrwzE4a0P6uWaDkKo+h8dFJcHU9j0DTfHeyQjqX2yd47NfwD/UUTTi790RgtByUY5YRN7shPwFZwrz3UeD4ps1tTmR+duKmJw8TROLWnNyuneKAIKPjh6/LkTG7b+VFxpkF7L5rK2/7cj5H46sq9KzNyhTH4xS2imKO+HfZt3tAsU0TmPv0lflrBQwPjhgOq3Gr26RxuQxZjQS+IZFNSEGkj82P98iuqsv0iQ8ENz1l22g0Wr41LqAwon2XsgnV1u0ow7yo3JKzEHriwqyS9vr3zI0mM7BP4yZNvuUw0Mg7vAgCuPygCrBeSHUSWJJzWawVEGhPfVIlFVv/V7OqJc9Pfl1MSHscw6yjPk2rw3BiTVTBNbhBPhBzSv5B6lLF64kBWdpDtcU6fJzYqhg="
  code_climate:
    repo_token: "78b2ef44b209e261840b5013783d07b61f367884a3adb33406a0256e57412e22"
branches:
  only:
  - master
  - develop
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  api_key:
    secure: UFoQ+NAVA5Ynm7hihxHKnSxfMuIlTwvVG5eUKmWZvAIfM3JwCWTbX6GpA5aIsqc9n7at128DLiITRk3H2e9UJlumH3WIU2tzWQb1+6irF7MaudAm49SgEcXG5AjEqIu5ikSXM4QCBNVdcZKQwW52GPL3j7owBWMPFf/8Lcgx24noZCXbK/K+RwCpYfpLQs/W4v8Sj4V8vHoSoVf4vyAmXWou3CyC6KVCAXJUjAIMHS3p1kbNecs5CgfXFVY/Gbfs0O0RmBFElaCd6WrljWil3TlVd/+iLATDWShzZE1ux8OUTBWBRGSnYs0U7QY/XWeensw0xAAky7E5R+DNHdr25tpllimMAzFJoCVeJXWXjUM04E71WFTdGT5Sk3Z5BYKKjc8fja81R551OlbD38wKyrDvs42vdFhX1KACzOtQ/aINz20qeEAEoppQ8sIglhwSdL2TI7gTv75vtKULZ8CQIjamW7mobgjT9pajNWdIrqaFT12szRkgv/LpAqRfBPP3S435JcZg7WQ88sEwKE/QV3NZ7+7HZ8BQ1kSih2AR1jLCD/nqKB4qtCgWE7eaMpne0bOyFHrI3dJVa+WRYYJOQzejFMCtdTMONrjMdtT6JEH9RRH+QAyMHCXRnqCCtKIIB6Q1NqEXYqNfRCI56/cPRHf+QQZFSCVb0I/6mbywvLM=
  app:
    master: spielplanismaning
    develop: spielplanismaning-testing
notifications:
  slack:
    on_pull_requests: false
    rooms:
      secure: iMFuDbqhVhvMxuWyrRx3xkhMXYchW9fYiVfWMMPdKqMdEAps9lpZ5W5pYkBgCCS+XDamVforN5zG1H8qrCkMkm8x+TXdM7FHOzgnlW+D8ufDXFoMF9kz4DR45fopHCUHJh3HM32zKqxEfPA5uiRN9dLf59dlogQ/TpX7h3fp2jrRGjDBLJw58hg0IwsZB3xQZkNzKT3qzQEdH2KRWB0Xgs1Ksan4PrD3ev9/d0vA0lpDHIJR7ynnnqdXIMs8DoFd+6fGLdvS6zZIXMNzdot46HvP1YoJEaw1p8Xcnk2EfAELQI2nnPFnzLv254+hAJAratzDuYA0VcjxJXx7/UOeFq4KoDfm1/K9puNOF4tZgGHi+PLOmqtFH52Un+zTQr9biW1nGq/UFLK4Ti+MrbwnL0i+i9uWBKC/2aVw0J1agxT3hJLqzi1qCsbXS/JqtRQrQhI4ZqRLU3Lz19CEmhezN2voTGIEyJZ6R2TQkzskr+Tg0sDgqMaX7tcVw4cdXCnFpLcYWKXsP+PMg0qEtSzA0Xn8zvW6E6KaAtLoJ1GBo6O8HLcSgMIzFIgwHN50SvTBY15Xu7dodS3K+WQu+OEP8tW3sum/o2f82MlytlsudbMcAVmctLMou/b7ThiIv1mFaVyFNUvBhtfz+Mq1CjJHkrBj65ne8c/9uE2V9j2F010=
  email:
    recipients:
      - b.wittmann@mail.de
    on_success: never
    on_failure: always