language: node_js
node_js:
- '6.3'
before_script:
- npm install
- bower install
script: gulp test
branches:
  only:
  - master
  - develop
deploy:
  provider: heroku
  api_key:
    secure: UFoQ+NAVA5Ynm7hihxHKnSxfMuIlTwvVG5eUKmWZvAIfM3JwCWTbX6GpA5aIsqc9n7at128DLiITRk3H2e9UJlumH3WIU2tzWQb1+6irF7MaudAm49SgEcXG5AjEqIu5ikSXM4QCBNVdcZKQwW52GPL3j7owBWMPFf/8Lcgx24noZCXbK/K+RwCpYfpLQs/W4v8Sj4V8vHoSoVf4vyAmXWou3CyC6KVCAXJUjAIMHS3p1kbNecs5CgfXFVY/Gbfs0O0RmBFElaCd6WrljWil3TlVd/+iLATDWShzZE1ux8OUTBWBRGSnYs0U7QY/XWeensw0xAAky7E5R+DNHdr25tpllimMAzFJoCVeJXWXjUM04E71WFTdGT5Sk3Z5BYKKjc8fja81R551OlbD38wKyrDvs42vdFhX1KACzOtQ/aINz20qeEAEoppQ8sIglhwSdL2TI7gTv75vtKULZ8CQIjamW7mobgjT9pajNWdIrqaFT12szRkgv/LpAqRfBPP3S435JcZg7WQ88sEwKE/QV3NZ7+7HZ8BQ1kSih2AR1jLCD/nqKB4qtCgWE7eaMpne0bOyFHrI3dJVa+WRYYJOQzejFMCtdTMONrjMdtT6JEH9RRH+QAyMHCXRnqCCtKIIB6Q1NqEXYqNfRCI56/cPRHf+QQZFSCVb0I/6mbywvLM=
  app:
    master: spielplanismaning
    develop: spielplanismaning-testing